(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const all = selector => [...document.querySelectorAll(selector)];
  const create = (tag, className = '', text) => { const n=document.createElement(tag); if(className)n.className=className; if(text!==undefined)n.textContent=text; return n; };
  const icon = (name, className = 'icon') => { const svg=document.createElementNS('http://www.w3.org/2000/svg','svg'); const use=document.createElementNS('http://www.w3.org/2000/svg','use'); svg.setAttribute('class',className); svg.setAttribute('aria-hidden','true'); use.setAttribute('href','#i-'+name); svg.append(use); return svg; };
  const CATEGORIES=['Electronics','Bottles','Keys','ID cards','Bags','Umbrellas','Other'];
  const ICONS={Electronics:'headphones',Bottles:'bottle',Keys:'keys','ID cards':'id',Bags:'bag',Umbrellas:'umbrella',Other:'box'};
  const THEMES={Electronics:'electronics',Bottles:'bottles',Keys:'keys','ID cards':'id',Bags:'bags',Umbrellas:'umbrellas',Other:'other'};
  const LOCAL_KEY='campusfind-offline-v2', OWNER_KEY='campusfind-owner-keys-v1';
  const SAMPLES=[
    {id:'demo-1',type:'found',title:'Blue steel water bottle',category:'Bottles',location:'Central Library',description:'A blue reusable steel bottle left near the reading tables. Tell the finder about its stickers before arranging a handover.',date:'2026-09-22'},
    {id:'demo-2',type:'lost',title:'Wireless headphones',category:'Electronics',location:'Student Centre',description:'Black over-ear headphones in a soft carry case. Last seen after the afternoon study session.',date:'2026-09-22'},
    {id:'demo-3',type:'found',title:'Keys with a green keyring',category:'Keys',location:'Engineering Block',description:'A small bunch of keys with a green keyring. Please confirm how many keys there are at the campus desk.',date:'2026-09-21'},
    {id:'demo-4',type:'found',title:'A very rainy-day umbrella',category:'Umbrellas',location:'Cafeteria',description:'A navy folding umbrella left by the cafeteria entrance after the rain.',date:'2026-09-21'},
    {id:'demo-5',type:'lost',title:'Blue water bottle',category:'Bottles',location:'Central Library',description:'I left my blue steel bottle at the library after a study group. It has a small sticker near the bottom.',date:'2026-09-20'},
    {id:'demo-6',type:'found',title:'Canvas backpack',category:'Bags',location:'Sports Complex',description:'A beige canvas backpack was handed in near the courts. The owner should describe its contents privately.',date:'2026-09-20'}
  ].map(i=>({...i,sample:true,status:'open',photo:'',contactEmail:'',createdAt:i.date+'T12:00:00+00:00'}));
  const state={mode:'connecting',demo:false,type:'all',category:'all',sort:'newest',search:'',offset:0,total:0,loading:false,seq:0,detailSeq:0,detailId:null,editing:null,photoUrl:null};
  let offlinePosts=[],ownerKeys={},storageAvailable=true,toastTimer,searchTimer;
  try { const list=JSON.parse(localStorage.getItem(LOCAL_KEY)||'[]'); if(Array.isArray(list))offlinePosts=list.filter(i=>i && !i.sample && typeof i.id==='string' && ['found','lost'].includes(i.type) && CATEGORIES.includes(i.category)).slice(0,200); } catch(_) { storageAvailable=false; }
  try { const saved=JSON.parse(localStorage.getItem(OWNER_KEY)||'{}'); if(saved && typeof saved==='object' && !Array.isArray(saved))ownerKeys=saved; } catch(_) { storageAvailable=false; }

  function localDate(){const d=new Date(); return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');}
  function dateText(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(String(value)))return 'Date not set'; const d=new Date(value+'T12:00:00');return Number.isNaN(d.getTime())?'Date not set':d.toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'});}
  function notify(message){const toast=$('toast');toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),4700);}
  function photoUrl(value){return typeof value==='string' && (/^\/uploads\/[0-9a-f]{36}\.jpg$/.test(value) || /^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(value)) ? value : '';}
  function validEmail(value){return typeof value==='string' && value.length<=160 && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);}
  function emailLink(address,subject){return 'mailto:'+encodeURIComponent(address)+'?subject='+encodeURIComponent(subject);}
  function ownerOf(item){return !item.sample && (state.mode==='offline' ? offlinePosts.some(i=>i.id===item.id) : typeof ownerKeys[item.id]==='string' && /^[a-f0-9]{64}$/.test(ownerKeys[item.id]));}
  function rememberOwner(id,token){if(!/^[a-f0-9]{64}$/.test(token))return;ownerKeys[id]=token;try{localStorage.setItem(OWNER_KEY,JSON.stringify(ownerKeys));}catch(_){notify('Save your private management link: browser storage is unavailable.');}}
  function forgetOwner(id){delete ownerKeys[id];try{localStorage.setItem(OWNER_KEY,JSON.stringify(ownerKeys));}catch(_) {}}
  function storeOffline(next){if(next.length>200)throw Error('This browser preview supports up to 200 of your own posts.');if(storageAvailable){try{localStorage.setItem(LOCAL_KEY,JSON.stringify(next));}catch(_){throw Error('Browser storage is full. Try a smaller photo or free up space.');}}offlinePosts=next;if(!storageAvailable)notify('Saved for this tab only. Browser storage is unavailable.');}
  function offlineAll(){return [...offlinePosts,...SAMPLES];}
  function banner(){const banner=$('modeBanner'), text=$('modeText');banner.classList.toggle('is-live',state.mode==='shared');$('retryBtn').hidden=state.mode!=='offline';if(state.mode==='shared'){text.textContent=state.demo?'Live shared demo · Sample listings are fictional; new posts are visible to anyone with this link.':'Shared community board · Posts are visible to anyone with this site’s link.';$('footerMode').textContent=state.demo?'Shared demo · Fictional samples labelled':'Shared community board';}else if(state.mode==='offline'){text.textContent='Offline browser preview · Sample listings are fictional. Your posts stay on this device only.';$('footerMode').textContent='Offline preview · Not shared across devices';}else{text.textContent='Connecting to the community board…';}}
  async function requestJSON(path,options){const response=await fetch(path,{...options,headers:{Accept:'application/json',...(options?.headers||{})}});let data;try{data=await response.json();}catch(_){throw Error('The server returned an unexpected response.');}if(!response.ok)throw Error(data.error||'Something went wrong. Please try again.');return data;}
  async function connect(){state.mode='connecting';banner();try{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),3400);let config;try{config=await requestJSON('/api/config',{signal:controller.signal});}finally{clearTimeout(timer);}if(!config.shared)throw Error('No shared board');state.mode='shared';state.demo=!!config.demo;}catch(_){state.mode='offline';state.demo=true;}banner();await loadItems(true);const linked=readManageLink()||new URLSearchParams(location.search).get('item');if(linked && /^[a-z0-9-]{4,80}$/i.test(linked))showDetail(linked,false);}
  function offlineList(){let found=offlineAll().filter(i=>i.status==='open');const terms=state.search.trim().toLocaleLowerCase().split(/\s+/).filter(Boolean);found=found.filter(i=>(state.type==='all'||i.type===state.type)&&(state.category==='all'||i.category===state.category)&&terms.every(t=>[i.title,i.location,i.description,i.category].join(' ').toLocaleLowerCase().includes(t)));found.sort((a,b)=>state.sort==='newest'?String(b.createdAt||b.date).localeCompare(String(a.createdAt||a.date)):String(a.createdAt||a.date).localeCompare(String(b.createdAt||b.date)));const allPosts=offlineAll();return {items:found.slice(state.offset,state.offset+9),count:found.length,hasMore:state.offset+9<found.length,stats:{found:allPosts.filter(i=>i.status==='open'&&i.type==='found').length,lost:allPosts.filter(i=>i.status==='open'&&i.type==='lost').length,reunited:allPosts.filter(i=>i.status==='reunited').length}};}
  function setMetrics(stats){$('foundCount').textContent=String(stats.found??0);$('lostCount').textContent=String(stats.lost??0);$('returnCount').textContent=String(stats.reunited??0);}
  function renderLoading(){const grid=$('grid');grid.replaceChildren();for(let i=0;i<3;i++)grid.append(create('div','loading-card'));grid.setAttribute('aria-busy','true');$('resultCount').textContent='Looking for listings…';$('loadMore').hidden=true;}
  function filterUI(){const active=Boolean(state.search.trim()||state.category!=='all'||state.type!=='all'||state.sort!=='newest');$('resetFilters').hidden=!active;$('clearSearch').hidden=!$('search').value;}
  async function loadItems(reset=true){if(!reset&&state.loading)return;const seq=++state.seq;if(reset){state.offset=0;renderLoading();}state.loading=true;filterUI();try{let response;if(state.mode==='shared'){const qs=new URLSearchParams({q:state.search,type:state.type,category:state.category,sort:state.sort,limit:'9',offset:String(state.offset)});response=await requestJSON('/api/items?'+qs);}else response=offlineList();if(seq!==state.seq)return;state.total=response.count;setMetrics(response.stats);const grid=$('grid');if(reset)grid.replaceChildren();for(const item of response.items)grid.append(makeCard(item));state.offset+=response.items.length;if(!state.total){showEmpty();}else{$('resultCount').innerHTML='Showing <strong>'+state.offset+'</strong> of <strong>'+state.total+'</strong> '+(state.total===1?'listing':'listings')+(state.demo?' · fictional samples clearly labelled':'');}grid.setAttribute('aria-busy','false');$('loadMore').hidden=!response.hasMore;}catch(error){if(seq!==state.seq)return;showError(error.message||'Could not load listings.');}finally{if(seq===state.seq)state.loading=false;}}
  function showEmpty(){const wrap=create('div','empty-state');const box=create('span','empty-icon');box.append(icon('search'));wrap.append(box,create('h3','','Nothing here yet.'),create('p','','Try a different search, or help the community by posting an item.'));const btn=create('button','button button-light','Clear filters');btn.type='button';btn.addEventListener('click',resetFilters);wrap.append(btn);$('grid').replaceChildren(wrap);$('resultCount').textContent='No listings match these filters.';}
  function showError(message){const wrap=create('div','empty-state');const box=create('span','empty-icon');box.append(icon('search'));wrap.append(box,create('h3','','Could not load the board'),create('p','',message));const btn=create('button','button button-light','Try again');btn.type='button';btn.addEventListener('click',()=>loadItems(true));wrap.append(btn);$('grid').replaceChildren(wrap);$('grid').setAttribute('aria-busy','false');$('resultCount').textContent='Connection interrupted';$('loadMore').hidden=true;}
  function makeMedia(item,detail=false){const n=create(detail?'div':'button',(detail?'detail-media':'card-media')+' theme-'+(THEMES[item.category]||'other'));if(!detail){n.type='button';n.setAttribute('aria-label','View '+item.type+' item: '+item.title);n.addEventListener('click',()=>showDetail(item.id));}const source=photoUrl(item.photo);function placeholder(){n.classList.remove('has-photo');n.append(icon(ICONS[item.category]||'box','icon category-icon'));}if(source){n.classList.add('has-photo');const img=create('img');img.src=source;img.alt=detail?'Photo of '+item.title:'';img.loading='lazy';img.onerror=()=>{img.remove();placeholder();};n.append(img);}else placeholder();if(!detail){const status=create('span','status-chip '+item.type,item.type);n.append(status);}if(item.sample)n.append(create('span','sample-chip','Fictional sample'));return n;}
  function makeCard(item){const card=create('article','item-card');card.append(makeMedia(item));const body=create('div','card-content');body.append(create('span','card-category',item.category),create('h3','',item.title),create('p','description',item.description||'No description yet.'));const meta=create('div','card-meta');const loc=create('span');loc.append(icon('pin'),create('span','location-name',item.location));const date=create('span');date.append(icon('calendar'),document.createTextNode(dateText(item.date)));meta.append(loc,date);body.append(meta);const foot=create('div','card-bottom');foot.append(create('span','',item.sample?'Demo listing':'Community post'));const view=create('button','','View details');view.type='button';view.setAttribute('aria-label','View details for '+item.title);view.append(icon('arrow'));view.addEventListener('click',()=>showDetail(item.id));foot.append(view);card.append(body,foot);return card;}
  function resetFilters(){clearTimeout(searchTimer);state.search='';state.type='all';state.category='all';state.sort='newest';$('search').value='';$('category').value='all';$('sort').value='newest';all('[data-type]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.type==='all')));loadItems(true);}

  function matchOffline(item){const stop=new Set(['the','and','with','for','was','near','from','this','that','have','lost','found','item','blue']);const words=s=>new Set((String(s).toLowerCase().match(/[\p{L}\p{N}]+/gu)||[]).filter(w=>w.length>2&&!stop.has(w)));const title=words(item.title),detail=words(item.description);return offlineAll().filter(i=>i.id!==item.id&&i.type!==item.type&&i.status==='open'&&i.sample===item.sample).map(i=>{let score=(i.category===item.category?4:0)+(i.location.toLowerCase()===item.location.toLowerCase()?3:0);for(const t of words(i.title))if(title.has(t))score+=2;for(const t of words(i.description))if(detail.has(t))score++;return {item:i,score};}).filter(x=>x.score>=5).sort((a,b)=>b.score-a.score).slice(0,3).map(x=>x.item);}
  async function itemDetail(id){if(state.mode==='shared')return requestJSON('/api/items/'+encodeURIComponent(id));const item=offlineAll().find(i=>i.id===id);if(!item)throw Error('This listing could not be found in this browser.');return {item,matches:item.status==='open'?matchOffline(item):[]};}
  function updateUrl(id){try{const url=new URL(location.href);if(id)url.searchParams.set('item',id);else url.searchParams.delete('item');history.replaceState(null,'',url);}catch(_) {}}
  function readManageLink(){try{const match=location.hash.match(/^#manage=([0-9a-f]{32})\.([0-9a-f]{64})$/);if(!match)return null;rememberOwner(match[1],match[2]);const url=new URL(location.href);url.hash='';url.searchParams.set('item',match[1]);history.replaceState(null,'',url);return match[1];}catch(_){return null;}}
  function modalOpen(dialog){if(dialog.open)return;dialog.showModal();document.body.classList.add('modal-open');}
  function modalClose(dialog){if(dialog.open)dialog.close();}
  function linkFor(id,privateLink=false){const url=new URL(location.href);url.searchParams.set('item',id);url.hash=privateLink?'manage='+id+'.'+ownerKeys[id]:'';return url.href;}
  async function copy(text,success){try{if(navigator.clipboard?.writeText && window.isSecureContext)await navigator.clipboard.writeText(text);else{const input=create('textarea');input.value=text;input.style.position='fixed';input.style.opacity='0';document.body.append(input);input.select();if(!document.execCommand('copy'))throw Error('clipboard blocked');input.remove();}notify(success);}catch(_){notify('Copy was blocked. Please copy the link from your browser’s address bar.');}}
  async function showDetail(id,pushUrl=true){const seq=++state.detailSeq;state.detailId=id;if($('postDialog').open)modalClose($('postDialog'));modalOpen($('detailDialog'));$('detailContent').replaceChildren(create('div','detail-loading','Loading this listing…'));if(pushUrl)updateUrl(id);try{const data=await itemDetail(id);if(seq!==state.detailSeq)return;renderDetail(data.item,data.matches||[]);}catch(error){if(seq!==state.detailSeq)return;const box=create('div','detail-error');box.append(create('h2','','Listing unavailable'),create('p','',error.message||'Please try again later.'));const back=create('button','button button-light','Close');back.type='button';back.addEventListener('click',()=>modalClose($('detailDialog')));box.append(back);$('detailContent').replaceChildren(box);}}
  function renderDetail(item,matches){const frame=create('div','detail-frame'),body=create('div','detail-body');frame.append(makeMedia(item,true));const head=create('div','detail-head');const status=create('span','status-chip '+item.type,item.type);head.append(status);if(item.status==='reunited')head.append(create('span','reunited-flag','✓ Reunited'));body.append(head,create('h2','',item.title));const meta=create('div','detail-meta'),place=create('span'),when=create('span');place.append(icon('pin'),document.createTextNode(item.location));when.append(icon('calendar'),document.createTextNode(dateText(item.date)));meta.append(place,when);body.append(meta,create('div','detail-subhead','About this item'),create('p','detail-desc',item.description||'No additional details.'));if(item.sample){const note=create('div','detail-note');note.append(icon('shield'),create('span','','This is a fictional sample, not a real item. Please don’t try to claim or contact its owner.'));body.append(note);}else{const note=create('div','detail-note');note.append(icon('shield'),create('span','','Verify an identifying detail privately and meet at a staffed campus desk. This site does not verify ownership.'));body.append(note);}
    const actions=create('div','detail-actions');if(!item.sample && item.status==='open' && state.mode==='shared'){
      const send=create('button','button','Send a private message');send.type='button';send.prepend(icon('mail'));send.addEventListener('click',()=>{const form=$('messageForm');form.hidden=!form.hidden;if(!form.hidden)form.querySelector('input[type=email]').focus();});actions.append(send);
      if(validEmail(item.contactEmail)){const mail=create('a','button button-light','Email reporter');mail.href=emailLink(item.contactEmail,'CampusFind: '+item.title);mail.prepend(icon('mail'));actions.append(mail);}
    }else if(!item.sample&&validEmail(item.contactEmail)){const mail=create('a','button button-light','Email reporter');mail.href=emailLink(item.contactEmail,'CampusFind: '+item.title);mail.prepend(icon('mail'));actions.append(mail);}
    if(state.mode==='shared'){const share=create('button','button button-light','Share listing');share.type='button';share.prepend(icon('share'));share.addEventListener('click',()=>copy(linkFor(item.id),'Public listing link copied.'));actions.append(share);}
    if(actions.children.length)body.append(actions);
    if(!item.sample && item.status==='open' && state.mode==='shared')body.append(buildMessageForm(item.id));
    if(item.status==='open'){const similar=create('section','similar');similar.append(create('h3','','Possible matches'),create('p','','Suggestions use shared keywords, category and location; they are not proof of ownership.'));if(matches.length){const list=create('div','similar-list');for(const m of matches){const b=create('button','similar-match');b.type='button';b.append(create('span','',m.title+' · '+m.location),icon('arrow'));b.addEventListener('click',()=>showDetail(m.id));list.append(b);}similar.append(list);}else similar.append(create('p','','Nothing similar yet. New posts may appear later.'));body.append(similar);}
    if(ownerOf(item))body.append(buildOwnerPanel(item));frame.append(body);$('detailContent').replaceChildren(frame);
  }
  function buildMessageForm(id){const form=create('form','message-form');form.id='messageForm';form.hidden=true;form.noValidate=true;const h=create('h3','','Send a private message');const intro=create('p','','Only the post owner can read your message and reply email. No automatic notification is sent.');form.append(h,intro);const labelEmail=create('label','form-label','Your reply email');const email=create('input');email.type='email';email.name='replyEmail';email.required=true;email.maxLength=160;email.placeholder='yourname@campus.edu';labelEmail.append(email);const labelBody=create('label','form-label','Your message');const body=create('textarea');body.name='message';body.required=true;body.minLength=12;body.maxLength=1000;body.placeholder='I think this may be mine. I can confirm a private identifying detail…';labelBody.append(body);const caution=create('p','message-caution','Don’t include passwords or ID numbers. The poster needs to check their private inbox to see your message.');const error=create('p','form-error');error.setAttribute('role','alert');const submit=create('button','button','Send message');submit.type='submit';submit.prepend(icon('arrow'));form.append(labelEmail,labelBody,caution,error,submit);form.addEventListener('submit',async event=>{event.preventDefault();error.textContent='';if(!form.reportValidity())return;const replyEmail=email.value.trim(),message=body.value.trim();if(!validEmail(replyEmail)||message.length<12){error.textContent='Enter a valid email and a message of at least 12 characters.';return;}submit.disabled=true;submit.textContent='Sending…';try{await requestJSON('/api/items/'+encodeURIComponent(id)+'/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({replyEmail,message})});form.replaceChildren(create('p','message-success','✓ Message saved in the owner’s private inbox. No automatic email is sent, so they’ll need to check it here.'));notify('Private message sent.');}catch(e){error.textContent=e.message||'Could not send your message.';}finally{submit.disabled=false;submit.textContent='Send message';}});return form;}
  function buildOwnerPanel(item){const panel=create('section','owner-panel');const title=create('h3');title.append(icon('shield'),document.createTextNode('Your private post controls'));panel.append(title,create('p','',state.mode==='shared'?'Save your management link somewhere private and check your inbox here. No email notifications are sent.':'This is stored only on this device; it will not appear on the shared board.'));const buttons=create('div','owner-buttons');if(state.mode==='shared'){const manage=create('button','','Copy management link');manage.type='button';manage.prepend(icon('share'));manage.addEventListener('click',()=>copy(linkFor(item.id,true),'Private management link copied. Keep it to yourself.'));buttons.append(manage);const inbox=create('button','','Check inbox');inbox.type='button';inbox.prepend(icon('mail'));inbox.addEventListener('click',()=>showInbox(item.id,panel,inbox));buttons.append(inbox);}if(item.status==='open'){const edit=create('button','','Edit post');edit.type='button';edit.prepend(icon('edit'));edit.addEventListener('click',()=>openPost(item.type,item));buttons.append(edit);const resolve=create('button','','Mark reunited');resolve.type='button';resolve.prepend(icon('check'));resolve.addEventListener('click',()=>resolveItem(item));buttons.append(resolve);}const del=create('button','danger','Delete');del.type='button';del.prepend(icon('trash'));del.addEventListener('click',()=>deleteItem(item));buttons.append(del);panel.append(buttons);return panel;}
  async function showInbox(id,panel,button){let box=panel.querySelector('.inbox');if(box){box.hidden=!box.hidden;return;}box=create('div','inbox');box.append(create('p','','Checking your inbox…'));panel.append(box);button.disabled=true;try{const data=await requestJSON('/api/items/'+encodeURIComponent(id)+'/messages',{headers:{'X-Manage-Token':ownerKeys[id]}});box.replaceChildren();if(!data.messages.length){box.append(create('p','','No messages yet. Check back here later.'));}for(const m of data.messages){const note=create('div','inbox-note');note.append(create('p','',m.message),create('span','',dateText(String(m.createdAt).slice(0,10))));if(validEmail(m.replyEmail)){const reply=create('a','','Reply by email →');reply.href=emailLink(m.replyEmail,'Re: CampusFind item');note.append(reply);}box.append(note);}}catch(e){box.replaceChildren(create('p','',e.message||'Could not load your inbox.'));}finally{button.disabled=false;}}
  async function resolveItem(item){if(!confirm('Mark this listing as reunited? It will leave the active community board.'))return;try{if(state.mode==='shared')await requestJSON('/api/items/'+encodeURIComponent(item.id)+'/resolve',{method:'POST',headers:{'X-Manage-Token':ownerKeys[item.id]}});else storeOffline(offlinePosts.map(i=>i.id===item.id?{...i,status:'reunited'}:i));modalClose($('detailDialog'));await loadItems(true);notify('Reunited! Thank you for helping bring it home.');}catch(e){notify(e.message||'Could not update this listing.');}}
  async function deleteItem(item){if(!confirm('Delete this listing and its messages permanently? This cannot be undone.'))return;try{if(state.mode==='shared')await requestJSON('/api/items/'+encodeURIComponent(item.id),{method:'DELETE',headers:{'X-Manage-Token':ownerKeys[item.id]}});else storeOffline(offlinePosts.filter(i=>i.id!==item.id));forgetOwner(item.id);modalClose($('detailDialog'));await loadItems(true);notify('Listing deleted.');}catch(e){notify(e.message||'Could not delete this listing.');}}

  function openPost(type='found',item=null){state.editing=item;const form=$('postForm');form.reset();$('formError').textContent='';$('itemDate').max=localDate();$('itemDate').value=localDate();if(state.photoUrl){URL.revokeObjectURL(state.photoUrl);state.photoUrl=null;}$('photoPreview').hidden=true;$('photoName').textContent='Add a photo';form.elements.namedItem('type').value=type;if(item){form.elements.namedItem('type').value=item.type;form.elements.namedItem('title').value=item.title;form.elements.namedItem('category').value=item.category;form.elements.namedItem('location').value=item.location;form.elements.namedItem('description').value=item.description;form.elements.namedItem('contactEmail').value=item.contactEmail||'';form.elements.namedItem('date').value=item.date;if(photoUrl(item.photo)){$('photoPreview').src=item.photo;$('photoPreview').hidden=false;$('photoName').textContent='Current photo (tap to replace)';}}$('postTitle').textContent=item?'Edit your post':type==='lost'?'Report a lost item':'Report a found item';$('saveButton').innerHTML=(item?'Save changes':'Post item')+' <svg class="icon" aria-hidden="true"><use href="#i-arrow"/></svg>';if($('detailDialog').open)modalClose($('detailDialog'));modalOpen($('postDialog'));setTimeout(()=>$('itemTitle').focus(),60);}
  function validateForm(form){if(!form.reportValidity())return 'Please complete the required fields.';if(!CATEGORIES.includes(form.elements.namedItem('category').value))return 'Choose a category.';if(form.elements.namedItem('title').value.trim().length<3)return 'Use at least 3 characters in the title.';if(form.elements.namedItem('location').value.trim().length<3)return 'Add a specific location.';if(form.elements.namedItem('description').value.trim().length<12)return 'Please add a description of at least 12 characters.';if(form.elements.namedItem('date').value>localDate())return 'Choose today or an earlier date.';const email=form.elements.namedItem('contactEmail').value.trim();if(email&&!validEmail(email))return 'Enter a valid public contact email or leave it blank.';const file=$('photo').files[0];if(file&&(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024))return 'Please choose a JPG, PNG or WebP under 5 MB.';return '';}
  async function compressPhoto(file){if(!file)return '';const rawUrl=URL.createObjectURL(file);try{const img=await new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(Error('This photo could not be read.'));image.src=rawUrl;});const scale=Math.min(1,1000/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const ctx=canvas.getContext('2d');if(!ctx)throw Error('Photo processing is unavailable in this browser.');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',.72);}finally{URL.revokeObjectURL(rawUrl);}}
  async function offlineSave(form,old){const data=new FormData(form);const file=$('photo').files[0];const newPhoto=file?await compressPhoto(file):old?.photo||'';const item={id:old?.id||(globalThis.crypto?.randomUUID?.()||'local-'+Date.now()+'-'+Math.random().toString(36).slice(2)),type:String(data.get('type')),title:String(data.get('title')).trim(),category:String(data.get('category')),date:String(data.get('date')),location:String(data.get('location')).trim(),description:String(data.get('description')).trim(),contactEmail:String(data.get('contactEmail')).trim(),photo:newPhoto,createdAt:old?.createdAt||new Date().toISOString(),status:old?.status||'open',sample:false};storeOffline(old?offlinePosts.map(i=>i.id===old.id?item:i):[item,...offlinePosts]);return {item};}
  async function savePost(e){e.preventDefault();const form=e.currentTarget,button=$('saveButton');if(button.disabled)return;const error=validateForm(form);if(error){$('formError').textContent=error;return;}$('formError').textContent='';button.disabled=true;const oldHtml=button.innerHTML;button.textContent=state.editing?'Saving changes…':'Posting item…';const original=state.editing;try{let data;if(state.mode==='shared'){data=await requestJSON('/api/items'+(original?'/'+encodeURIComponent(original.id):''),{method:original?'PATCH':'POST',headers:original?{'X-Manage-Token':ownerKeys[original.id]}:{},body:new FormData(form)});if(data.manageToken)rememberOwner(data.item.id,data.manageToken);}else data=await offlineSave(form,original);modalClose($('postDialog'));state.editing=null;await loadItems(true);await showDetail(data.item.id);notify(original?'Your listing has been updated.':state.mode==='shared'?'Posted on the shared board. Save your private management link!':'Saved in this browser preview only.');}catch(ex){$('formError').textContent=ex.message||'Could not save this post. Please try again.';}finally{button.disabled=false;button.innerHTML=oldHtml;}}

  function wire(){
    $('year').textContent=String(new Date().getFullYear());$('itemDate').max=localDate();$('itemDate').value=localDate();
    all('[data-post]').forEach(b=>b.addEventListener('click',()=>openPost(b.dataset.post)));
    $('menuToggle').addEventListener('click',()=>{const menu=$('mobileLinks');menu.hidden=!menu.hidden;$('menuToggle').setAttribute('aria-expanded',String(!menu.hidden));$('menuToggle').setAttribute('aria-label',menu.hidden?'Open navigation':'Close navigation');});
    all('#mobileLinks a').forEach(a=>a.addEventListener('click',()=>{$('mobileLinks').hidden=true;$('menuToggle').setAttribute('aria-expanded','false');}));
    $('heroBrowse').addEventListener('click',()=>setTimeout(()=>$('search').focus({preventScroll:true}),420));
    $('retryBtn').addEventListener('click',connect);
    $('search').addEventListener('input',()=>{state.search=$('search').value;filterUI();clearTimeout(searchTimer);searchTimer=setTimeout(()=>loadItems(true),250);});
    $('clearSearch').addEventListener('click',()=>{clearTimeout(searchTimer);$('search').value='';state.search='';$('search').focus();loadItems(true);});
    all('[data-type]').forEach(b=>b.addEventListener('click',()=>{state.type=b.dataset.type;all('[data-type]').forEach(t=>t.setAttribute('aria-pressed',String(t===b)));loadItems(true);}));
    $('category').addEventListener('change',()=>{state.category=$('category').value;loadItems(true);});
    $('sort').addEventListener('change',()=>{state.sort=$('sort').value;loadItems(true);});
    $('resetFilters').addEventListener('click',resetFilters);
    $('loadMore').addEventListener('click',()=>loadItems(false));
    $('postClose').addEventListener('click',()=>modalClose($('postDialog')));$('postCancel').addEventListener('click',()=>modalClose($('postDialog')));
    $('detailClose').addEventListener('click',()=>modalClose($('detailDialog')));
    [$('postDialog'),$('detailDialog')].forEach(d=>{d.addEventListener('click',e=>{if(e.target===d)modalClose(d);});d.addEventListener('close',()=>{if(d===$('detailDialog')){state.detailSeq++;state.detailId=null;updateUrl(null);}if(!$('postDialog').open&&!$('detailDialog').open)document.body.classList.remove('modal-open');if(d===$('postDialog')&&state.photoUrl){URL.revokeObjectURL(state.photoUrl);state.photoUrl=null;}});});
    $('photo').addEventListener('change',()=>{const file=$('photo').files[0];if(state.photoUrl){URL.revokeObjectURL(state.photoUrl);state.photoUrl=null;}if(!file){$('photoPreview').hidden=true;$('photoName').textContent='Add a photo';return;}if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){$('formError').textContent='Choose a JPG, PNG or WebP smaller than 5 MB.';$('photo').value='';return;}$('formError').textContent='';$('photoName').textContent=file.name;state.photoUrl=URL.createObjectURL(file);$('photoPreview').src=state.photoUrl;$('photoPreview').hidden=false;});
    $('postForm').addEventListener('submit',savePost);
    all('input[name="type"]').forEach(r=>r.addEventListener('change',()=>{if(!state.editing)$('postTitle').textContent=r.value==='found'?'Report a found item':'Report a lost item';}));
  }
  wire();connect();
})();
